# Project identification
sonar.projectKey=DecSecOps-Udemy-
sonar.projectName=DecSecOps-Udemy-
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Files/folders to ignore
sonar.exclusions=**/node_modules/**
